// <auto-generated />
using System;
using AstronautSatelliteAPI.DataPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstronautSatelliteAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421170412_AddAstronautSatellitesTable")]
    partial class AddAstronautSatellitesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstronautSatellite", b =>
                {
                    b.Property<long>("AstronautsId")
                        .HasColumnType("bigint");

                    b.Property<long>("SatellitesId")
                        .HasColumnType("bigint");

                    b.HasKey("AstronautsId", "SatellitesId");

                    b.HasIndex("SatellitesId");

                    b.ToTable("AstronautSatellites", (string)null);
                });

            modelBuilder.Entity("AstronautSatelliteAPI.Models.Astronaut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Astronauts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExperienceYears = 12,
                            FirstName = "Neil",
                            LastName = "Armstrong"
                        },
                        new
                        {
                            Id = 2L,
                            ExperienceYears = 8,
                            FirstName = "Sally",
                            LastName = "Ride"
                        },
                        new
                        {
                            Id = 3L,
                            ExperienceYears = 15,
                            FirstName = "Chris",
                            LastName = "Hadfield"
                        });
                });

            modelBuilder.Entity("AstronautSatelliteAPI.Models.Satellite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Decommissioned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrbitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Satellites");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Decommissioned = false,
                            LaunchDate = new DateTime(1990, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hubble",
                            OrbitType = "LEO"
                        },
                        new
                        {
                            Id = 2L,
                            Decommissioned = false,
                            LaunchDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Starlink-17",
                            OrbitType = "MEO"
                        },
                        new
                        {
                            Id = 3L,
                            Decommissioned = true,
                            LaunchDate = new DateTime(2020, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sentinel-6",
                            OrbitType = "LEO"
                        });
                });

            modelBuilder.Entity("AstronautSatellite", b =>
                {
                    b.HasOne("AstronautSatelliteAPI.Models.Astronaut", null)
                        .WithMany()
                        .HasForeignKey("AstronautsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AstronautSatelliteAPI.Models.Satellite", null)
                        .WithMany()
                        .HasForeignKey("SatellitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
